### ISSUE TITLE
Android app crashes when backgrounded

### ISSUE THREAD

**Issue by stevenconner** [newrelic/newrelic-react-native-agent#183]
## Description

When the app is backgrounded, the app crashes, causing a complete reload when opening it back up.

## Steps to Reproduce

Open the app, background the app, it crashes and produces the below error.

## Expected Behavior

It should not crash.

## Relevant Logs / Console output

java.lang.NoSuchMethodError: No virtual method stop()V in class Lcom/newrelic/agent/android/ndk/AgentNDK; or its super classes (declaration of 'com.newrelic.agent.android.ndk.AgentNDK' appears in /data/app/~~voxjon9IRU0FLKyGh_e7cQ==/com.webstaurantstore.storefront.dev-O78eY7CtNsubxiYDpikzFw==/base.apk!classes3.dex)
  com.newrelic.agent.android.ndk.NativeReporting.stop(NativeReporting.java:97)
  com.newrelic.agent.android.ndk.NativeReporting.shutdown(NativeReporting.java:49)
  com.newrelic.agent.android.AndroidAgentImpl.stop(AndroidAgentImpl.java:589)
  com.newrelic.agent.android.AndroidAgentImpl.stop(AndroidAgentImpl.java:521)
  com.newrelic.agent.android.AndroidAgentImpl.applicationBackgrounded(AndroidAgentImpl.java:681)
  com.newrelic.agent.android.background.ApplicationStateMonitor.notifyApplicationInBackground(ApplicationStateMonitor.java:102)
  com.newrelic.agent.android.background.ApplicationStateMonitor.lambda$uiHidden$0$com-newrelic-agent-android-background-ApplicationStateMonitor(ApplicationStateMonitor.java:63)
  com.newrelic.agent.android.background.ApplicationStateMonitor$$ExternalSyntheticLambda0.run(Unknown Source:2)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
  java.lang.Thread.run(Thread.java:1012)

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Output of `npx react-native info`:
System:
  OS: macOS 14.6
  CPU: (12) arm64 Apple M2 Pro
  Memory: 395.34 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: ~/.nvm/versions/node/v18.17.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v18.17.0/bin/yarn
  npm:
    version: 9.6.7
    path: ~/.nvm/versions/node/v18.17.0/bin/npm
  Watchman:
    version: 2024.06.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /Users/sconner/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-33 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-35 | Google APIs ARM 64 v8a
      - android-35 | Google Play ARM 64 v8a
      - android-35 | Google APIs Experimental 16k Page Size ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/sconner/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

Which platform is the issue happening on? (Android, iOS, tvOS, etc.):
Android

Any conflicting packages installed?
Not that i know of

**Comment by ndesai-newrelic** [comment]
@stevenconner we are aware about this issue, we will fix it next release.

**Comment by stevenconner** [comment]
@ndesai-newrelic  thanks!!!

**Comment by naveene1** [comment]
We also getting same issue on the android build when going to background. Please provide a immediate fix

Thanks in advance.

**Comment by ndesai-newrelic** [comment]
@naveene1 this will fix in next release.

**Comment by vlimag** [comment]
just fyi - Im seeing an issue when app is running low on memory and app goes to background then foreground.
might be related

**Comment by ndesai-newrelic** [comment]
@naveene1 it is fixed in latest react native agent, can you check it?

**Comment by DarshanSavaliyaGitHub** [comment]
I'm still facing this crash. with the latest version also...

**Comment by ndesai-newrelic** [comment]
@DarshanSavaliyaGitHub the ndk agent release is pending, it will release soon after that your issue will be fixed.

**Comment by vlimag** [comment]
@ndesai-newrelic is the ndk agent updated under the hood? or do we need to reinstall / update the new relic sdk after thats released? would you update once thats released pls?

**Comment by vlimag** [comment]
cool cool, thanks. any ETA for the release @ndesai-newrelic ?

**Comment by JPStrydom** [comment]
Do we know when this will get fixed? 

This is currently causing production issues on some of our systems. Is there any potential workaround like perhaps downgrading `newrelic-react-native-agent`?

**Comment by NurRachman** [comment]
> @naveene1 it is fixed in latest react native agent, can you check it?

hi @naveene1 already update to 1.4.3, still crash on background

java.lang.NoSuchMethodError: No virtual method stop()Z in class Lcom/newrelic/agent/android/ndk/AgentNDK; or its super classes (declaration of 'com.newrelic.agent.android.ndk.AgentNDK'

**Comment by jeremyvz** [comment]
ETA for the issue being resolved?

**Comment by ClaudiaSkyeB** [comment]
This is affecting my team too and causing me emotional distress >.< any update? please fix

**Comment by KyleTheHarrison** [comment]
We need this fix asap. It has been such a nightmare finding alternative solutions.

**Comment by irfaanf** [comment]
ETA for a fix for this? @ndesai-newrelic

**Comment by itajenglish** [comment]
+1

**Comment by itajenglish** [comment]
+1 Same issue
https://listedb.sentry.io/share/issue/225827c1c8e4428fb62bbdc84e5a4a81

**Comment by lukaszkurantdev** [comment]
It's connected to `1.1.1` version of NewRelic NDK. When I've moved to the previous version it works without error.

Patch:
```js
diff --git a/node_modules/newrelic-react-native-agent/package.json b/node_modules/newrelic-react-native-agent/package.json
index 19119d3..32316f5 100644
--- a/node_modules/newrelic-react-native-agent/package.json
+++ b/node_modules/newrelic-react-native-agent/package.json
@@ -96,7 +96,7 @@
     },
     "android": {
       "newrelic": "7.5.+",
-      "ndk": "1.1.+"
+      "ndk": "1.1.0"
     }
   }
 }

```

**Comment by fkrein1** [comment]
Are there any updates on this issue? I downgraded to version 1.3.8, and the app is working fine. However, in newer releases, the app crashes in the background on Android. I’m using Expo 51 with prebuild and the New Relic plugin.

**Comment by danarchos** [comment]
We reduced our crash rate 10x by removing New Relic. What a joke!

**Comment by ywang-nr** [comment]
This is fixed in the latest Android NDK v1.1.2 release.

**Comment by JohnnyBravoFromTexas** [comment]
1.1.2 release [notes](https://docs.newrelic.com/docs/release-notes/mobile-release-notes/android-release-notes/android-ndk-112/)

**Comment by KyleTheHarrison** [comment]
Hi Felipe,

Please update the app to the latest version. Everything is working fine on 1.3.10.

Best regards,
Kyle Harrison

**Comment by ladp333** [comment]
> This is fixed in the latest Android NDK v1.1.2 release.

@ywang-nr The real question is if `1.1.2` is available in the latest newrelic-react-native-agent ? if not, do you expect us to patch the package? or else what is the right way to include the NDK in a bare-bones cli react-native project os that we can update the ndk seperately?
fyi: I tested the latest newrelic-react-native-agent (1.4.3) with RN 0.74.5 a couple of days ago and it crashed.

`Fatal Exception: java.lang.NoSuchMethodError: No virtual method stop()Z in class Lcom/newrelic/agent/android/ndk/AgentNDK; or its super classes (declaration of 'com.newrelic.agent.android.ndk.AgentNDK' appears in /data/app/~~UXfp2ZvKcxmNz4l0MYNIOg==/com.originmobileapp-et4-xbWwrBKQebcKoc_EfQ==/base.apk!classes5.dex) at com.newrelic.agent.android.ndk.NativeReporting.stop(NativeReporting.java:108) at com.newrelic.agent.android.ndk.NativeReporting.shutdown(NativeReporting.java:53) at com.newrelic.agent.android.AndroidAgentImpl.stop(AndroidAgentImpl.java:589) at com.newrelic.agent.android.AndroidAgentImpl.stop(AndroidAgentImpl.java:521) at com.newrelic.agent.android.AndroidAgentImpl.applicationBackgrounded(AndroidAgentImpl.java:681) at com.newrelic.agent.android.background.ApplicationStateMonitor.notifyApplicationInBackground(ApplicationStateMonitor.java:102) at com.newrelic.agent.android.background.ApplicationStateMonitor.lambda$uiHidden$0$com-newrelic-agent-android-background-ApplicationStateMonitor(ApplicationStateMonitor.java:63) at com.newrelic.agent.android.background.ApplicationStateMonitor$$ExternalSyntheticLambda0.run(:2) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) at java.lang.Thread.run(Thread.java:1012)`


This is my 2 cents about this SDK.

This is not the first time we’ve had issues with this SDK. Considering how common these use cases are, I can’t believe how the team releases the SDK. They probably don’t test it properly. If they did, they wouldn’t miss these bugs. To be honest, I have lost confidence in this SDK and have decided to disable it for now. I’m sorry to say that the quality of this SDK is very low, and I didn’t expect such a poor-quality product from New Relic. Either the team needs to step up their game or hand it over to a more capable team within the company. We are paying top dollar to New Relic.

**Comment by itajenglish** [comment]
> > This is fixed in the latest Android NDK v1.1.2 release.
> 
> 
> 
> @ywang-nr The real question is if `1.1.2` is available in the latest newrelic-react-native-agent ? if not, do you expect us to patch the package? or else what is the right way to include the NDK in a bare-bones cli react-native project os that we can update the ndk seperately?
> 
> fyi: I tested the latest newrelic-react-native-agent (1.4.3) with RN 0.74.5 a couple of days ago and it crashed.
> 
> 
> 
> `Fatal Exception: java.lang.NoSuchMethodError: No virtual method stop()Z in class Lcom/newrelic/agent/android/ndk/AgentNDK; or its super classes (declaration of 'com.newrelic.agent.android.ndk.AgentNDK' appears in /data/app/~~UXfp2ZvKcxmNz4l0MYNIOg==/com.originmobileapp-et4-xbWwrBKQebcKoc_EfQ==/base.apk!classes5.dex) at com.newrelic.agent.android.ndk.NativeReporting.stop(NativeReporting.java:108) at com.newrelic.agent.android.ndk.NativeReporting.shutdown(NativeReporting.java:53) at com.newrelic.agent.android.AndroidAgentImpl.stop(AndroidAgentImpl.java:589) at com.newrelic.agent.android.AndroidAgentImpl.stop(AndroidAgentImpl.java:521) at com.newrelic.agent.android.AndroidAgentImpl.applicationBackgrounded(AndroidAgentImpl.java:681) at com.newrelic.agent.android.background.ApplicationStateMonitor.notifyApplicationInBackground(ApplicationStateMonitor.java:102) at com.newrelic.agent.android.background.ApplicationStateMonitor.lambda$uiHidden$0$com-newrelic-agent-android-background-ApplicationStateMonitor(ApplicationStateMonitor.java:63) at com.newrelic.agent.android.background.ApplicationStateMonitor$$ExternalSyntheticLambda0.run(:2) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) at java.lang.Thread.run(Thread.java:1012)`
> 
> 
> 
> 
> 
> This is my 2 cents about this SDK.
> 
> 
> 
> This is not the first time we’ve had issues with this SDK. Considering how common these use cases are, I can’t believe how the team releases the SDK. They probably don’t test it properly. If they did, they wouldn’t miss these bugs. To be honest, I have lost confidence in this SDK and have decided to disable it for now. I’m sorry to say that the quality of this SDK is very low, and I didn’t expect such a poor-quality product from New Relic. Either the team needs to step up their game or hand it over to a more capable team within the company. We are paying top dollar to New Relic.

I have to agree with this! Very standard things are also missing from this SDK/Product like automatic source map upload and React Navigation screen names and metrics in the UI. I have moved away from New Relic for React Native RUM. The team needs to step up their game if they want to compete otherwise they should stop supporting React Native in my opinion.

**Comment by ladp333** [comment]
> > > This is fixed in the latest Android NDK v1.1.2 release.
> > 
> > 
> > @ywang-nr The real question is if `1.1.2` is available in the latest newrelic-react-native-agent ? if not, do you expect us to patch the package? or else what is the right way to include the NDK in a bare-bones cli react-native project os that we can update the ndk seperately?
> > fyi: I tested the latest newrelic-react-native-agent (1.4.3) with RN 0.74.5 a couple of days ago and it crashed.
> > `Fatal Exception: java.lang.NoSuchMethodError: No virtual method stop()Z in class Lcom/newrelic/agent/android/ndk/AgentNDK; or its super classes (declaration of 'com.newrelic.agent.android.ndk.AgentNDK' appears in /data/app/~~UXfp2ZvKcxmNz4l0MYNIOg==/com.originmobileapp-et4-xbWwrBKQebcKoc_EfQ==/base.apk!classes5.dex) at com.newrelic.agent.android.ndk.NativeReporting.stop(NativeReporting.java:108) at com.newrelic.agent.android.ndk.NativeReporting.shutdown(NativeReporting.java:53) at com.newrelic.agent.android.AndroidAgentImpl.stop(AndroidAgentImpl.java:589) at com.newrelic.agent.android.AndroidAgentImpl.stop(AndroidAgentImpl.java:521) at com.newrelic.agent.android.AndroidAgentImpl.applicationBackgrounded(AndroidAgentImpl.java:681) at com.newrelic.agent.android.background.ApplicationStateMonitor.notifyApplicationInBackground(ApplicationStateMonitor.java:102) at com.newrelic.agent.android.background.ApplicationStateMonitor.lambda$uiHidden$0$com-newrelic-agent-android-background-ApplicationStateMonitor(ApplicationStateMonitor.java:63) at com.newrelic.agent.android.background.ApplicationStateMonitor$$ExternalSyntheticLambda0.run(:2) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) at java.lang.Thread.run(Thread.java:1012)`
> > This is my 2 cents about this SDK.
> > This is not the first time we’ve had issues with this SDK. Considering how common these use cases are, I can’t believe how the team releases the SDK. They probably don’t test it properly. If they did, they wouldn’t miss these bugs. To be honest, I have lost confidence in this SDK and have decided to disable it for now. I’m sorry to say that the quality of this SDK is very low, and I didn’t expect such a poor-quality product from New Relic. Either the team needs to step up their game or hand it over to a more capable team within the company. We are paying top dollar to New Relic.
> 
> I have to agree with this! Very standard things are also missing from this SDK/Product like automatic source map upload and React Navigation screen names and metrics in the UI. I have moved away from New Relic for React Native RUM. The team needs to step up their game if they want to compete, otherwise they should stop supporting React Native in my opinion.

Exactly. 100%

**Comment by AbdulBsit** [comment]
Still crashing for me after upgrade to NDK Agent 1.1.2

**Comment by arelstone** [comment]
I experience this too.. I have created a support ticket with the NR support team

**Comment by YuriLima23** [comment]
I Fixed this problem downgrade to version newrelic-react-native-agent 1.3.6, and verify if yarn.lock is the correct version

**Comment by ndesai-newrelic** [comment]
the issue is fixed in 1.4.4.

# Regarding the Recent Application Crash Issue

We sincerely apologize for the inconvenience caused by the recent application crashes when transitioning to the background. We understand your frustration, and we'd like to provide a detailed explanation of what occurred and the steps we're taking to prevent similar issues in the future.

## Root Cause

The issue arose due to a complex interaction between our Android and NDK agent releases:

1. We use a "+" convention for version numbering of both Android and NDK agents, which automatically pulls the latest versions during builds.
2. The Android and NDK agents were released in quick succession.
3. Our testing did not catch the scenario where a newer NDK agent was paired with an older Android agent.

This led to a method not found error, initially misdiagnosed as an NDK-side issue. Our attempt to resolve it by reverting NDK changes in an NDK agent release did not address the core problem: a version mismatch between the Android and NDK agents.

## Our Response and Future Prevention

To prevent similar issues in the future, we are implementing the following measures:

1. More comprehensive testing scenarios on version compatibility between components.
2. Modifying our release process to ensure thorough validation of all agent combinations.
3. Reconsidering our use of the "+" convention for version numbers to have more predictable builds.

## Moving Forward

We value your trust and are committed to delivering a stable and reliable React Native agent. We will conduct more thorough testing for future releases to prevent such issues from recurring.

If you need any additional information or clarification regarding this issue, please don't hesitate to reach out. We're here to address any concerns you may have.

Thank you for your patience and understanding as we work to improve our product and processes.
