### ISSUE TITLE
No virtual method stop()Z in class Lcom/newrelic/agent/android/ndk/AgentNDK; or its super classes (declaration of 'com.newrelic.agent.android.ndk.AgentNDK' appears in /data/app/~~4MCTCLx4S1im03NbkvLoZA==/com.adaptedmind.mobile-n--cX-mCUAL0oqY6lZzaKQ==/base.apk!classes3.dex)

### ISSUE THREAD

**Issue by ethanneff** [newrelic/newrelic-react-native-agent#199]
getting production crashes when upgrading from 1.4.1 to 1.4.3

```
NoSuchMethodError
No virtual method stop()Z in class Lcom/newrelic/agent/android/ndk/AgentNDK; or its super classes (declaration of 'com.newrelic.agent.android.ndk.AgentNDK' appears in /data/app/~~4MCTCLx4S1im03NbkvLoZA==/com.adaptedmind.mobile-n--cX-mCUAL0oqY6lZzaKQ==/base.apk!classes3.dex)
```

**Comment by ethanneff** [comment]
this package is not stable 

![Screenshot 15](https://github.com/user-attachments/assets/4be536ad-22cf-4300-8058-e9e10db4a0af)

**Comment by jamesmcn1** [comment]
This is also happening for us.

**Comment by ndesai-newrelic** [comment]
@ethanneff can you check newrelic ndk and newrelic android agent version for this? it should be 1.1.1 and 7.5.1 for react native agent version 1.4.3.

**Comment by jamesmcn1** [comment]
I am getting these crashes with:

 "newrelic-react-native-agent": "1.4.1",
 
 classpath "com.newrelic.agent.android:agent-gradle-plugin:7.5.0"

**Comment by ndesai-newrelic** [comment]
@jamesmcn1  we fixed this issue in 1.4.4. 

you can find detailed explanation for this issue here.
https://github.com/newrelic/newrelic-react-native-agent/issues/195#issuecomment-2327422787

**Comment by ndesai-newrelic** [comment]
@ethanneff please update it to 1.4.4.

**Comment by ethanneff** [comment]
We deleted New Relic and migrated to Sentry. We cannot risk this again.
